{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "pygame 2.3.0 (SDL 2.24.2, Python 3.10.4)\n",
      "Hello from the pygame community. https://www.pygame.org/contribute.html\n",
      "['/home/quanta/.conda/envs/forl-proj/lib/python3.10/site-packages/ray/thirdparty_files', '/home/quanta/Projects/FoRL-project/test_code', '/home/quanta/.conda/envs/forl-proj/lib/python310.zip', '/home/quanta/.conda/envs/forl-proj/lib/python3.10', '/home/quanta/.conda/envs/forl-proj/lib/python3.10/lib-dynload', '', '/home/quanta/.conda/envs/forl-proj/lib/python3.10/site-packages', '/home/quanta/Projects/FoRL-project']\n"
     ]
    }
   ],
   "source": [
    "import os\n",
    "import sys\n",
    "\n",
    "import gymnasium as gym\n",
    "import numpy as np\n",
    "import ray\n",
    "import torch\n",
    "from gymnasium import spaces\n",
    "from ray import tune\n",
    "from ray.rllib.algorithms.dqn import DQN, DQNConfig\n",
    "from ray.rllib.models import ModelCatalog\n",
    "from ray.rllib.models.torch.torch_modelv2 import TorchModelV2\n",
    "from ray.rllib.utils.exploration.epsilon_greedy import EpsilonGreedy\n",
    "from ray.tune.registry import register_env\n",
    "from torch import nn\n",
    "\n",
    "module_path = os.path.abspath(os.path.join('..'))\n",
    "if module_path not in sys.path:\n",
    "    sys.path.append(module_path)\n",
    "\n",
    "import core\n",
    "print(sys.path)\n",
    "\n",
    "sys.modules['core'] = core\n",
    "from core.algorithms.amd.amd import AMD, AMDConfig\n",
    "from core.algorithms.amd.wrappers import \\\n",
    "    MultiAgentEnvFromPettingZooParallel as P2M\n",
    "from core.environments.wolfpack import wolfpack_env_creator"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "class SimpleMLPModelV2(TorchModelV2, nn.Module):\n",
    "\n",
    "    def __init__(self, obs_space: gym.Space, act_space: gym.Space, num_outputs, *args, **kwargs):\n",
    "        TorchModelV2.__init__(self, obs_space, act_space, num_outputs, *args, **kwargs)\n",
    "        nn.Module.__init__(self)\n",
    "\n",
    "        self.flattened_obs_space = spaces.flatten_space(obs_space)\n",
    "        self.obs_space = obs_space\n",
    "        self.action_space = act_space\n",
    "\n",
    "        self.model = nn.Sequential(\n",
    "            nn.Flatten(start_dim=1, end_dim=-1),\n",
    "            nn.Linear(self.flattened_obs_space.shape[0], 128),\n",
    "            nn.ReLU(),\n",
    "            nn.Linear(128, 32),\n",
    "            nn.ReLU(),\n",
    "        )\n",
    "\n",
    "        self.policy_fn = nn.Linear(32, num_outputs)\n",
    "        self.value_fn = nn.Linear(32, 1)\n",
    "\n",
    "    def forward(self, input_dict, state, seq_lens):\n",
    "        model_out = self.model(input_dict[\"obs\"].to(torch.float32) / 255)\n",
    "        self._value_out = self.value_fn(model_out)\n",
    "        return self.policy_fn(model_out), state\n",
    "\n",
    "    def value_function(self):\n",
    "        return self._value_out.flatten()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-05-21 12:41:09,054\tINFO worker.py:1553 -- Started a local Ray instance.\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "    <div style=\"margin-left: 50px;display: flex;flex-direction: row;align-items: center\">\n",
       "        <h3 style=\"color: var(--jp-ui-font-color0)\">Ray</h3>\n",
       "        <svg version=\"1.1\" id=\"ray\" width=\"3em\" viewBox=\"0 0 144.5 144.6\" style=\"margin-left: 3em;margin-right: 3em\">\n",
       "            <g id=\"layer-1\">\n",
       "                <path fill=\"#00a2e9\" class=\"st0\" d=\"M97.3,77.2c-3.8-1.1-6.2,0.9-8.3,5.1c-3.5,6.8-9.9,9.9-17.4,9.6S58,88.1,54.8,81.2c-1.4-3-3-4-6.3-4.1\n",
       "                    c-5.6-0.1-9.9,0.1-13.1,6.4c-3.8,7.6-13.6,10.2-21.8,7.6C5.2,88.4-0.4,80.5,0,71.7c0.1-8.4,5.7-15.8,13.8-18.2\n",
       "                    c8.4-2.6,17.5,0.7,22.3,8c1.3,1.9,1.3,5.2,3.6,5.6c3.9,0.6,8,0.2,12,0.2c1.8,0,1.9-1.6,2.4-2.8c3.5-7.8,9.7-11.8,18-11.9\n",
       "                    c8.2-0.1,14.4,3.9,17.8,11.4c1.3,2.8,2.9,3.6,5.7,3.3c1-0.1,2,0.1,3,0c2.8-0.5,6.4,1.7,8.1-2.7s-2.3-5.5-4.1-7.5\n",
       "                    c-5.1-5.7-10.9-10.8-16.1-16.3C84,38,81.9,37.1,78,38.3C66.7,42,56.2,35.7,53,24.1C50.3,14,57.3,2.8,67.7,0.5\n",
       "                    C78.4-2,89,4.7,91.5,15.3c0.1,0.3,0.1,0.5,0.2,0.8c0.7,3.4,0.7,6.9-0.8,9.8c-1.7,3.2-0.8,5,1.5,7.2c6.7,6.5,13.3,13,19.8,19.7\n",
       "                    c1.8,1.8,3,2.1,5.5,1.2c9.1-3.4,17.9-0.6,23.4,7c4.8,6.9,4.6,16.1-0.4,22.9c-5.4,7.2-14.2,9.9-23.1,6.5c-2.3-0.9-3.5-0.6-5.1,1.1\n",
       "                    c-6.7,6.9-13.6,13.7-20.5,20.4c-1.8,1.8-2.5,3.2-1.4,5.9c3.5,8.7,0.3,18.6-7.7,23.6c-7.9,5-18.2,3.8-24.8-2.9\n",
       "                    c-6.4-6.4-7.4-16.2-2.5-24.3c4.9-7.8,14.5-11,23.1-7.8c3,1.1,4.7,0.5,6.9-1.7C91.7,98.4,98,92.3,104.2,86c1.6-1.6,4.1-2.7,2.6-6.2\n",
       "                    c-1.4-3.3-3.8-2.5-6.2-2.6C99.8,77.2,98.9,77.2,97.3,77.2z M72.1,29.7c5.5,0.1,9.9-4.3,10-9.8c0-0.1,0-0.2,0-0.3\n",
       "                    C81.8,14,77,9.8,71.5,10.2c-5,0.3-9,4.2-9.3,9.2c-0.2,5.5,4,10.1,9.5,10.3C71.8,29.7,72,29.7,72.1,29.7z M72.3,62.3\n",
       "                    c-5.4-0.1-9.9,4.2-10.1,9.7c0,0.2,0,0.3,0,0.5c0.2,5.4,4.5,9.7,9.9,10c5.1,0.1,9.9-4.7,10.1-9.8c0.2-5.5-4-10-9.5-10.3\n",
       "                    C72.6,62.3,72.4,62.3,72.3,62.3z M115,72.5c0.1,5.4,4.5,9.7,9.8,9.9c5.6-0.2,10-4.8,10-10.4c-0.2-5.4-4.6-9.7-10-9.7\n",
       "                    c-5.3-0.1-9.8,4.2-9.9,9.5C115,72.1,115,72.3,115,72.5z M19.5,62.3c-5.4,0.1-9.8,4.4-10,9.8c-0.1,5.1,5.2,10.4,10.2,10.3\n",
       "                    c5.6-0.2,10-4.9,9.8-10.5c-0.1-5.4-4.5-9.7-9.9-9.6C19.6,62.3,19.5,62.3,19.5,62.3z M71.8,134.6c5.9,0.2,10.3-3.9,10.4-9.6\n",
       "                    c0.5-5.5-3.6-10.4-9.1-10.8c-5.5-0.5-10.4,3.6-10.8,9.1c0,0.5,0,0.9,0,1.4c-0.2,5.3,4,9.8,9.3,10\n",
       "                    C71.6,134.6,71.7,134.6,71.8,134.6z\"/>\n",
       "            </g>\n",
       "        </svg>\n",
       "        <table>\n",
       "            <tr>\n",
       "                <td style=\"text-align: left\"><b>Python version:</b></td>\n",
       "                <td style=\"text-align: left\"><b>3.10.4</b></td>\n",
       "            </tr>\n",
       "            <tr>\n",
       "                <td style=\"text-align: left\"><b>Ray version:</b></td>\n",
       "                <td style=\"text-align: left\"><b> 2.3.1</b></td>\n",
       "            </tr>\n",
       "            \n",
       "        </table>\n",
       "    </div>\n",
       "</div>\n"
      ],
      "text/plain": [
       "RayContext(dashboard_url='', python_version='3.10.4', ray_version='2.3.1', ray_commit='5f14cee8dfc6d61ec4fd3bc2c440f9944e92b33a', address_info={'node_ip_address': '192.168.3.2', 'raylet_ip_address': '192.168.3.2', 'redis_address': None, 'object_store_address': '/tmp/ray/session_2023-05-21_12-41-07_327074_41809/sockets/plasma_store', 'raylet_socket_name': '/tmp/ray/session_2023-05-21_12-41-07_327074_41809/sockets/raylet', 'webui_url': '', 'session_dir': '/tmp/ray/session_2023-05-21_12-41-07_327074_41809', 'metrics_export_port': 40816, 'gcs_address': '192.168.3.2:58645', 'address': '192.168.3.2:58645', 'dashboard_agent_listen_port': 52365, 'node_id': 'b0c71db01c8a783b45fad49e9d7c5f9a0bcc536938d994313948f3b6'})"
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "ray.init()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "# register env and model\n",
    "env_name = 'wolfpack'\n",
    "register_env(env_name, lambda config: P2M(wolfpack_env_creator(config)))\n",
    "ModelCatalog.register_custom_model(\"SimpleMLPModelV2\", SimpleMLPModelV2)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "# config for dqn\n",
    "config = DQNConfig().multi_agent(\n",
    "    policies=['predator', 'prey'],\n",
    "    policy_mapping_fn=(lambda agent_id, *args, **kwargs: {\n",
    "        'wolf_1': 'predator',\n",
    "        'wolf_2': 'predator',\n",
    "        'prey': 'prey',\n",
    "    }[agent_id]),\n",
    ").environment(\n",
    "    env=env_name,\n",
    "    env_config={\n",
    "        'r_lone': 1.0,\n",
    "        'r_team': 5.0,\n",
    "        'r_prey': 0.0,\n",
    "        'coop_radius': 4,\n",
    "        'max_cycles': 1000,\n",
    "    },\n",
    "    clip_actions=True,\n",
    ").rollouts(\n",
    "    num_rollout_workers=4,\n",
    "    rollout_fragment_length=128,\n",
    ").training(\n",
    "    model={\n",
    "        \"custom_model\": \"SimpleMLPModelV2\",\n",
    "        \"custom_model_config\": {},\n",
    "    },\n",
    "    train_batch_size=1000,\n",
    "    lr=2e-5,\n",
    "    gamma=0.99,\n",
    "    v_min=0.0,\n",
    "    v_max=10.0,\n",
    "    # double_q=True,\n",
    ").debugging(log_level=\"ERROR\").framework(framework=\"torch\").resources(\n",
    "    num_gpus=int(os.environ.get(\"RLLIB_NUM_GPUS\", \"0\")),\n",
    "    num_cpus_per_worker=3,\n",
    ")\n",
    "explore_config = {\n",
    "    \"type\": EpsilonGreedy,\n",
    "    \"initial_epsilon\": 1.0,\n",
    "    \"final_epsilon\": 0.1,\n",
    "    \"epsilon_timesteps\": 100000,\n",
    "}\n",
    "config.explore = True,\n",
    "config.exploration_config = explore_config"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-05-21 12:41:10,439\tINFO algorithm.py:506 -- Current log_level is ERROR. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=46213)\u001b[0m 2023-05-21 12:41:13,810\tERROR serialization.py:371 -- No module named 'core'\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=46213)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=46213)\u001b[0m   File \"/home/quanta/.conda/envs/forl-proj/lib/python3.10/site-packages/ray/_private/serialization.py\", line 369, in deserialize_objects\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=46213)\u001b[0m     obj = self._deserialize_object(data, metadata, object_ref)\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=46213)\u001b[0m   File \"/home/quanta/.conda/envs/forl-proj/lib/python3.10/site-packages/ray/_private/serialization.py\", line 252, in _deserialize_object\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=46213)\u001b[0m     return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=46213)\u001b[0m   File \"/home/quanta/.conda/envs/forl-proj/lib/python3.10/site-packages/ray/_private/serialization.py\", line 207, in _deserialize_msgpack_data\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=46213)\u001b[0m     python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=46213)\u001b[0m   File \"/home/quanta/.conda/envs/forl-proj/lib/python3.10/site-packages/ray/_private/serialization.py\", line 197, in _deserialize_pickle5_data\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=46213)\u001b[0m     obj = pickle.loads(in_band)\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=46213)\u001b[0m ModuleNotFoundError: No module named 'core'\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=46212)\u001b[0m 2023-05-21 12:41:13,776\tERROR serialization.py:371 -- No module named 'core'\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=46212)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=46212)\u001b[0m   File \"/home/quanta/.conda/envs/forl-proj/lib/python3.10/site-packages/ray/_private/serialization.py\", line 369, in deserialize_objects\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=46212)\u001b[0m     obj = self._deserialize_object(data, metadata, object_ref)\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=46212)\u001b[0m   File \"/home/quanta/.conda/envs/forl-proj/lib/python3.10/site-packages/ray/_private/serialization.py\", line 252, in _deserialize_object\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=46212)\u001b[0m     return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=46212)\u001b[0m   File \"/home/quanta/.conda/envs/forl-proj/lib/python3.10/site-packages/ray/_private/serialization.py\", line 207, in _deserialize_msgpack_data\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=46212)\u001b[0m     python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=46212)\u001b[0m   File \"/home/quanta/.conda/envs/forl-proj/lib/python3.10/site-packages/ray/_private/serialization.py\", line 197, in _deserialize_pickle5_data\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=46212)\u001b[0m     obj = pickle.loads(in_band)\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=46212)\u001b[0m ModuleNotFoundError: No module named 'core'\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=46212)\u001b[0m 2023-05-21 12:41:13,807\tERROR worker.py:772 -- Exception raised in creation task: The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=46212, ip=192.168.3.2, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x7f15926c9e10>)\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=46212)\u001b[0m   At least one of the input arguments for this task could not be computed:\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=46212)\u001b[0m ray.exceptions.RaySystemError: System error: No module named 'core'\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=46212)\u001b[0m traceback: Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=46212)\u001b[0m ModuleNotFoundError: No module named 'core'\n",
      "2023-05-21 12:41:13,901\tERROR actor_manager.py:496 -- Ray error, taking actor 1 out of service. The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=46212, ip=192.168.3.2, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x7f15926c9e10>)\n",
      "  At least one of the input arguments for this task could not be computed:\n",
      "ray.exceptions.RaySystemError: System error: No module named 'core'\n",
      "traceback: Traceback (most recent call last):\n",
      "ModuleNotFoundError: No module named 'core'\n",
      "2023-05-21 12:41:13,902\tERROR actor_manager.py:496 -- Ray error, taking actor 2 out of service. The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=46213, ip=192.168.3.2, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x7f7535061db0>)\n",
      "  At least one of the input arguments for this task could not be computed:\n",
      "ray.exceptions.RaySystemError: System error: No module named 'core'\n",
      "traceback: Traceback (most recent call last):\n",
      "ModuleNotFoundError: No module named 'core'\n",
      "2023-05-21 12:41:13,902\tERROR actor_manager.py:496 -- Ray error, taking actor 3 out of service. The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=46214, ip=192.168.3.2, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x7ff6a1879ea0>)\n",
      "  At least one of the input arguments for this task could not be computed:\n",
      "ray.exceptions.RaySystemError: System error: No module named 'core'\n",
      "traceback: Traceback (most recent call last):\n",
      "ModuleNotFoundError: No module named 'core'\n",
      "2023-05-21 12:41:13,903\tERROR actor_manager.py:496 -- Ray error, taking actor 4 out of service. The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=46215, ip=192.168.3.2, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x7f44f5421de0>)\n",
      "  At least one of the input arguments for this task could not be computed:\n",
      "ray.exceptions.RaySystemError: System error: No module named 'core'\n",
      "traceback: Traceback (most recent call last):\n",
      "ModuleNotFoundError: No module named 'core'\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=46215)\u001b[0m 2023-05-21 12:41:13,867\tERROR serialization.py:371 -- No module named 'core'\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=46215)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=46215)\u001b[0m   File \"/home/quanta/.conda/envs/forl-proj/lib/python3.10/site-packages/ray/_private/serialization.py\", line 369, in deserialize_objects\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=46215)\u001b[0m     obj = self._deserialize_object(data, metadata, object_ref)\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=46215)\u001b[0m   File \"/home/quanta/.conda/envs/forl-proj/lib/python3.10/site-packages/ray/_private/serialization.py\", line 252, in _deserialize_object\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=46215)\u001b[0m     return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=46215)\u001b[0m   File \"/home/quanta/.conda/envs/forl-proj/lib/python3.10/site-packages/ray/_private/serialization.py\", line 207, in _deserialize_msgpack_data\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=46215)\u001b[0m     python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=46215)\u001b[0m   File \"/home/quanta/.conda/envs/forl-proj/lib/python3.10/site-packages/ray/_private/serialization.py\", line 197, in _deserialize_pickle5_data\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=46215)\u001b[0m     obj = pickle.loads(in_band)\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=46215)\u001b[0m ModuleNotFoundError: No module named 'core'\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=46215)\u001b[0m 2023-05-21 12:41:13,899\tERROR worker.py:772 -- Exception raised in creation task: The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=46215, ip=192.168.3.2, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x7f44f5421de0>)\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=46215)\u001b[0m   At least one of the input arguments for this task could not be computed:\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=46215)\u001b[0m ray.exceptions.RaySystemError: System error: No module named 'core'\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=46215)\u001b[0m traceback: Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=46215)\u001b[0m ModuleNotFoundError: No module named 'core'\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=46214)\u001b[0m 2023-05-21 12:41:13,843\tERROR serialization.py:371 -- No module named 'core'\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=46214)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=46214)\u001b[0m   File \"/home/quanta/.conda/envs/forl-proj/lib/python3.10/site-packages/ray/_private/serialization.py\", line 369, in deserialize_objects\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=46214)\u001b[0m     obj = self._deserialize_object(data, metadata, object_ref)\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=46214)\u001b[0m   File \"/home/quanta/.conda/envs/forl-proj/lib/python3.10/site-packages/ray/_private/serialization.py\", line 252, in _deserialize_object\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=46214)\u001b[0m     return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=46214)\u001b[0m   File \"/home/quanta/.conda/envs/forl-proj/lib/python3.10/site-packages/ray/_private/serialization.py\", line 207, in _deserialize_msgpack_data\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=46214)\u001b[0m     python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=46214)\u001b[0m   File \"/home/quanta/.conda/envs/forl-proj/lib/python3.10/site-packages/ray/_private/serialization.py\", line 197, in _deserialize_pickle5_data\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=46214)\u001b[0m     obj = pickle.loads(in_band)\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=46214)\u001b[0m ModuleNotFoundError: No module named 'core'\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=46214)\u001b[0m 2023-05-21 12:41:13,874\tERROR worker.py:772 -- Exception raised in creation task: The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=46214, ip=192.168.3.2, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x7ff6a1879ea0>)\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=46214)\u001b[0m   At least one of the input arguments for this task could not be computed:\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=46214)\u001b[0m ray.exceptions.RaySystemError: System error: No module named 'core'\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=46214)\u001b[0m traceback: Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=46214)\u001b[0m ModuleNotFoundError: No module named 'core'\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=46213)\u001b[0m 2023-05-21 12:41:13,840\tERROR worker.py:772 -- Exception raised in creation task: The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=46213, ip=192.168.3.2, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x7f7535061db0>)\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=46213)\u001b[0m   At least one of the input arguments for this task could not be computed:\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=46213)\u001b[0m ray.exceptions.RaySystemError: System error: No module named 'core'\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=46213)\u001b[0m traceback: Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=46213)\u001b[0m ModuleNotFoundError: No module named 'core'\n"
     ]
    },
    {
     "ename": "RaySystemError",
     "evalue": "System error: No module named 'core'\ntraceback: Traceback (most recent call last):\n  File \"/home/quanta/.conda/envs/forl-proj/lib/python3.10/site-packages/ray/_private/serialization.py\", line 369, in deserialize_objects\n    obj = self._deserialize_object(data, metadata, object_ref)\n  File \"/home/quanta/.conda/envs/forl-proj/lib/python3.10/site-packages/ray/_private/serialization.py\", line 252, in _deserialize_object\n    return self._deserialize_msgpack_data(data, metadata_fields)\n  File \"/home/quanta/.conda/envs/forl-proj/lib/python3.10/site-packages/ray/_private/serialization.py\", line 207, in _deserialize_msgpack_data\n    python_objects = self._deserialize_pickle5_data(pickle5_data)\n  File \"/home/quanta/.conda/envs/forl-proj/lib/python3.10/site-packages/ray/_private/serialization.py\", line 197, in _deserialize_pickle5_data\n    obj = pickle.loads(in_band)\nModuleNotFoundError: No module named 'core'\n",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mRayActorError\u001b[0m                             Traceback (most recent call last)",
      "File \u001b[0;32m~/.conda/envs/forl-proj/lib/python3.10/site-packages/ray/rllib/evaluation/worker_set.py:170\u001b[0m, in \u001b[0;36mWorkerSet.__init__\u001b[0;34m(self, env_creator, validate_env, default_policy_class, config, num_workers, local_worker, logdir, _setup, policy_class, trainer_config)\u001b[0m\n\u001b[1;32m    169\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m--> 170\u001b[0m     \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_setup(\n\u001b[1;32m    171\u001b[0m         validate_env\u001b[39m=\u001b[39;49mvalidate_env,\n\u001b[1;32m    172\u001b[0m         config\u001b[39m=\u001b[39;49mconfig,\n\u001b[1;32m    173\u001b[0m         num_workers\u001b[39m=\u001b[39;49mnum_workers,\n\u001b[1;32m    174\u001b[0m         local_worker\u001b[39m=\u001b[39;49mlocal_worker,\n\u001b[1;32m    175\u001b[0m     )\n\u001b[1;32m    176\u001b[0m \u001b[39m# WorkerSet creation possibly fails, if some (remote) workers cannot\u001b[39;00m\n\u001b[1;32m    177\u001b[0m \u001b[39m# be initialized properly (due to some errors in the RolloutWorker's\u001b[39;00m\n\u001b[1;32m    178\u001b[0m \u001b[39m# constructor).\u001b[39;00m\n",
      "File \u001b[0;32m~/.conda/envs/forl-proj/lib/python3.10/site-packages/ray/rllib/evaluation/worker_set.py:240\u001b[0m, in \u001b[0;36mWorkerSet._setup\u001b[0;34m(self, validate_env, config, num_workers, local_worker)\u001b[0m\n\u001b[1;32m    239\u001b[0m \u001b[39m# Create a number of @ray.remote workers.\u001b[39;00m\n\u001b[0;32m--> 240\u001b[0m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49madd_workers(\n\u001b[1;32m    241\u001b[0m     num_workers,\n\u001b[1;32m    242\u001b[0m     validate\u001b[39m=\u001b[39;49mconfig\u001b[39m.\u001b[39;49mvalidate_workers_after_construction,\n\u001b[1;32m    243\u001b[0m )\n\u001b[1;32m    245\u001b[0m \u001b[39m# If num_workers > 0 and we don't have an env on the local worker,\u001b[39;00m\n\u001b[1;32m    246\u001b[0m \u001b[39m# get the observation- and action spaces for each policy from\u001b[39;00m\n\u001b[1;32m    247\u001b[0m \u001b[39m# the first remote worker (which does have an env).\u001b[39;00m\n",
      "File \u001b[0;32m~/.conda/envs/forl-proj/lib/python3.10/site-packages/ray/rllib/evaluation/worker_set.py:614\u001b[0m, in \u001b[0;36mWorkerSet.add_workers\u001b[0;34m(self, num_workers, validate)\u001b[0m\n\u001b[1;32m    613\u001b[0m \u001b[39mif\u001b[39;00m \u001b[39mnot\u001b[39;00m result\u001b[39m.\u001b[39mok:\n\u001b[0;32m--> 614\u001b[0m     \u001b[39mraise\u001b[39;00m result\u001b[39m.\u001b[39mget()\n",
      "File \u001b[0;32m~/.conda/envs/forl-proj/lib/python3.10/site-packages/ray/rllib/utils/actor_manager.py:477\u001b[0m, in \u001b[0;36mFaultTolerantActorManager.__fetch_result\u001b[0;34m(self, remote_actor_ids, remote_calls, timeout_seconds, return_obj_refs, mark_healthy)\u001b[0m\n\u001b[1;32m    476\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m--> 477\u001b[0m     result \u001b[39m=\u001b[39m ray\u001b[39m.\u001b[39;49mget(r)\n\u001b[1;32m    478\u001b[0m     remote_results\u001b[39m.\u001b[39madd_result(actor_id, ResultOrError(result\u001b[39m=\u001b[39mresult))\n",
      "File \u001b[0;32m~/.conda/envs/forl-proj/lib/python3.10/site-packages/ray/_private/client_mode_hook.py:105\u001b[0m, in \u001b[0;36mclient_mode_hook.<locals>.wrapper\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m    104\u001b[0m         \u001b[39mreturn\u001b[39;00m \u001b[39mgetattr\u001b[39m(ray, func\u001b[39m.\u001b[39m\u001b[39m__name__\u001b[39m)(\u001b[39m*\u001b[39margs, \u001b[39m*\u001b[39m\u001b[39m*\u001b[39mkwargs)\n\u001b[0;32m--> 105\u001b[0m \u001b[39mreturn\u001b[39;00m func(\u001b[39m*\u001b[39;49margs, \u001b[39m*\u001b[39;49m\u001b[39m*\u001b[39;49mkwargs)\n",
      "File \u001b[0;32m~/.conda/envs/forl-proj/lib/python3.10/site-packages/ray/_private/worker.py:2382\u001b[0m, in \u001b[0;36mget\u001b[0;34m(object_refs, timeout)\u001b[0m\n\u001b[1;32m   2381\u001b[0m         \u001b[39melse\u001b[39;00m:\n\u001b[0;32m-> 2382\u001b[0m             \u001b[39mraise\u001b[39;00m value\n\u001b[1;32m   2384\u001b[0m \u001b[39mif\u001b[39;00m is_individual_id:\n",
      "\u001b[0;31mRayActorError\u001b[0m: The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=46212, ip=192.168.3.2, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x7f15926c9e10>)\n  At least one of the input arguments for this task could not be computed:\nray.exceptions.RaySystemError: System error: No module named 'core'\ntraceback: Traceback (most recent call last):\nModuleNotFoundError: No module named 'core'",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[0;31mRaySystemError\u001b[0m                            Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[6], line 2\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[39m# load checkpoint init weight\u001b[39;00m\n\u001b[0;32m----> 2\u001b[0m algo \u001b[39m=\u001b[39m config\u001b[39m.\u001b[39;49mbuild()\u001b[39m.\u001b[39mload_checkpoint(\u001b[39m'\u001b[39m\u001b[39m/home/quanta/ray_results/wolfpack/dqn/DQN_wolfpack_5e5a5_00000_0_2023-05-21_12-22-20/checkpoint_000010\u001b[39m\u001b[39m'\u001b[39m)\n\u001b[1;32m      4\u001b[0m \u001b[39m# worker = algo.workers.local_worker()\u001b[39;00m\n\u001b[1;32m      5\u001b[0m \u001b[39m# policy_map = worker.policy_map()\u001b[39;00m\n\u001b[1;32m      6\u001b[0m \u001b[39m# for policy_id in policy_map.keys():\u001b[39;00m\n\u001b[1;32m      7\u001b[0m \u001b[39m#     print(policy_id)\u001b[39;00m\n",
      "File \u001b[0;32m~/.conda/envs/forl-proj/lib/python3.10/site-packages/ray/rllib/algorithms/algorithm_config.py:926\u001b[0m, in \u001b[0;36mAlgorithmConfig.build\u001b[0;34m(self, env, logger_creator, use_copy)\u001b[0m\n\u001b[1;32m    923\u001b[0m \u001b[39mif\u001b[39;00m \u001b[39misinstance\u001b[39m(\u001b[39mself\u001b[39m\u001b[39m.\u001b[39malgo_class, \u001b[39mstr\u001b[39m):\n\u001b[1;32m    924\u001b[0m     algo_class \u001b[39m=\u001b[39m get_trainable_cls(\u001b[39mself\u001b[39m\u001b[39m.\u001b[39malgo_class)\n\u001b[0;32m--> 926\u001b[0m \u001b[39mreturn\u001b[39;00m algo_class(\n\u001b[1;32m    927\u001b[0m     config\u001b[39m=\u001b[39;49m\u001b[39mself\u001b[39;49m \u001b[39mif\u001b[39;49;00m \u001b[39mnot\u001b[39;49;00m use_copy \u001b[39melse\u001b[39;49;00m copy\u001b[39m.\u001b[39;49mdeepcopy(\u001b[39mself\u001b[39;49m),\n\u001b[1;32m    928\u001b[0m     logger_creator\u001b[39m=\u001b[39;49m\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mlogger_creator,\n\u001b[1;32m    929\u001b[0m )\n",
      "File \u001b[0;32m~/.conda/envs/forl-proj/lib/python3.10/site-packages/ray/rllib/algorithms/algorithm.py:445\u001b[0m, in \u001b[0;36mAlgorithm.__init__\u001b[0;34m(self, config, env, logger_creator, **kwargs)\u001b[0m\n\u001b[1;32m    433\u001b[0m \u001b[39m# Initialize common evaluation_metrics to nan, before they become\u001b[39;00m\n\u001b[1;32m    434\u001b[0m \u001b[39m# available. We want to make sure the metrics are always present\u001b[39;00m\n\u001b[1;32m    435\u001b[0m \u001b[39m# (although their values may be nan), so that Tune does not complain\u001b[39;00m\n\u001b[1;32m    436\u001b[0m \u001b[39m# when we use these as stopping criteria.\u001b[39;00m\n\u001b[1;32m    437\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mevaluation_metrics \u001b[39m=\u001b[39m {\n\u001b[1;32m    438\u001b[0m     \u001b[39m\"\u001b[39m\u001b[39mevaluation\u001b[39m\u001b[39m\"\u001b[39m: {\n\u001b[1;32m    439\u001b[0m         \u001b[39m\"\u001b[39m\u001b[39mepisode_reward_max\u001b[39m\u001b[39m\"\u001b[39m: np\u001b[39m.\u001b[39mnan,\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m    442\u001b[0m     }\n\u001b[1;32m    443\u001b[0m }\n\u001b[0;32m--> 445\u001b[0m \u001b[39msuper\u001b[39;49m()\u001b[39m.\u001b[39;49m\u001b[39m__init__\u001b[39;49m(\n\u001b[1;32m    446\u001b[0m     config\u001b[39m=\u001b[39;49mconfig,\n\u001b[1;32m    447\u001b[0m     logger_creator\u001b[39m=\u001b[39;49mlogger_creator,\n\u001b[1;32m    448\u001b[0m     \u001b[39m*\u001b[39;49m\u001b[39m*\u001b[39;49mkwargs,\n\u001b[1;32m    449\u001b[0m )\n\u001b[1;32m    451\u001b[0m \u001b[39m# Check, whether `training_iteration` is still a tune.Trainable property\u001b[39;00m\n\u001b[1;32m    452\u001b[0m \u001b[39m# and has not been overridden by the user in the attempt to implement the\u001b[39;00m\n\u001b[1;32m    453\u001b[0m \u001b[39m# algos logic (this should be done now inside `training_step`).\u001b[39;00m\n\u001b[1;32m    454\u001b[0m \u001b[39mtry\u001b[39;00m:\n",
      "File \u001b[0;32m~/.conda/envs/forl-proj/lib/python3.10/site-packages/ray/tune/trainable/trainable.py:169\u001b[0m, in \u001b[0;36mTrainable.__init__\u001b[0;34m(self, config, logger_creator, remote_checkpoint_dir, custom_syncer, sync_timeout)\u001b[0m\n\u001b[1;32m    167\u001b[0m start_time \u001b[39m=\u001b[39m time\u001b[39m.\u001b[39mtime()\n\u001b[1;32m    168\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_local_ip \u001b[39m=\u001b[39m ray\u001b[39m.\u001b[39mutil\u001b[39m.\u001b[39mget_node_ip_address()\n\u001b[0;32m--> 169\u001b[0m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49msetup(copy\u001b[39m.\u001b[39;49mdeepcopy(\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mconfig))\n\u001b[1;32m    170\u001b[0m setup_time \u001b[39m=\u001b[39m time\u001b[39m.\u001b[39mtime() \u001b[39m-\u001b[39m start_time\n\u001b[1;32m    171\u001b[0m \u001b[39mif\u001b[39;00m setup_time \u001b[39m>\u001b[39m SETUP_TIME_THRESHOLD:\n",
      "File \u001b[0;32m~/.conda/envs/forl-proj/lib/python3.10/site-packages/ray/rllib/algorithms/algorithm.py:571\u001b[0m, in \u001b[0;36mAlgorithm.setup\u001b[0;34m(self, config)\u001b[0m\n\u001b[1;32m    564\u001b[0m \u001b[39m# Only if user did not override `_init()`:\u001b[39;00m\n\u001b[1;32m    565\u001b[0m \u001b[39mif\u001b[39;00m _init \u001b[39mis\u001b[39;00m \u001b[39mFalse\u001b[39;00m:\n\u001b[1;32m    566\u001b[0m     \u001b[39m# - Create rollout workers here automatically.\u001b[39;00m\n\u001b[1;32m    567\u001b[0m     \u001b[39m# - Run the execution plan to create the local iterator to `next()`\u001b[39;00m\n\u001b[1;32m    568\u001b[0m     \u001b[39m#   in each training iteration.\u001b[39;00m\n\u001b[1;32m    569\u001b[0m     \u001b[39m# This matches the behavior of using `build_trainer()`, which\u001b[39;00m\n\u001b[1;32m    570\u001b[0m     \u001b[39m# has been deprecated.\u001b[39;00m\n\u001b[0;32m--> 571\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mworkers \u001b[39m=\u001b[39m WorkerSet(\n\u001b[1;32m    572\u001b[0m         env_creator\u001b[39m=\u001b[39;49m\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49menv_creator,\n\u001b[1;32m    573\u001b[0m         validate_env\u001b[39m=\u001b[39;49m\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mvalidate_env,\n\u001b[1;32m    574\u001b[0m         default_policy_class\u001b[39m=\u001b[39;49m\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mget_default_policy_class(\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mconfig),\n\u001b[1;32m    575\u001b[0m         config\u001b[39m=\u001b[39;49m\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mconfig,\n\u001b[1;32m    576\u001b[0m         num_workers\u001b[39m=\u001b[39;49m\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mconfig\u001b[39m.\u001b[39;49mnum_rollout_workers,\n\u001b[1;32m    577\u001b[0m         local_worker\u001b[39m=\u001b[39;49m\u001b[39mTrue\u001b[39;49;00m,\n\u001b[1;32m    578\u001b[0m         logdir\u001b[39m=\u001b[39;49m\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mlogdir,\n\u001b[1;32m    579\u001b[0m     )\n\u001b[1;32m    581\u001b[0m     \u001b[39m# TODO (avnishn): Remove the execution plan API by q1 2023\u001b[39;00m\n\u001b[1;32m    582\u001b[0m     \u001b[39m# Function defining one single training iteration's behavior.\u001b[39;00m\n\u001b[1;32m    583\u001b[0m     \u001b[39mif\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mconfig\u001b[39m.\u001b[39m_disable_execution_plan_api:\n\u001b[1;32m    584\u001b[0m         \u001b[39m# Ensure remote workers are initially in sync with the local worker.\u001b[39;00m\n",
      "File \u001b[0;32m~/.conda/envs/forl-proj/lib/python3.10/site-packages/ray/rllib/evaluation/worker_set.py:192\u001b[0m, in \u001b[0;36mWorkerSet.__init__\u001b[0;34m(self, env_creator, validate_env, default_policy_class, config, num_workers, local_worker, logdir, _setup, policy_class, trainer_config)\u001b[0m\n\u001b[1;32m    179\u001b[0m \u001b[39mexcept\u001b[39;00m RayActorError \u001b[39mas\u001b[39;00m e:\n\u001b[1;32m    180\u001b[0m     \u001b[39m# In case of an actor (remote worker) init failure, the remote worker\u001b[39;00m\n\u001b[1;32m    181\u001b[0m     \u001b[39m# may still exist and will be accessible, however, e.g. calling\u001b[39;00m\n\u001b[1;32m    182\u001b[0m     \u001b[39m# its `sample.remote()` would result in strange \"property not found\"\u001b[39;00m\n\u001b[1;32m    183\u001b[0m     \u001b[39m# errors.\u001b[39;00m\n\u001b[1;32m    184\u001b[0m     \u001b[39mif\u001b[39;00m e\u001b[39m.\u001b[39mactor_init_failed:\n\u001b[1;32m    185\u001b[0m         \u001b[39m# Raise the original error here that the RolloutWorker raised\u001b[39;00m\n\u001b[1;32m    186\u001b[0m         \u001b[39m# during its construction process. This is to enforce transparency\u001b[39;00m\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m    190\u001b[0m         \u001b[39m# - e.args[0].args[2]: The original Exception (e.g. a ValueError due\u001b[39;00m\n\u001b[1;32m    191\u001b[0m         \u001b[39m# to a config mismatch) thrown inside the actor.\u001b[39;00m\n\u001b[0;32m--> 192\u001b[0m         \u001b[39mraise\u001b[39;00m e\u001b[39m.\u001b[39margs[\u001b[39m0\u001b[39m]\u001b[39m.\u001b[39margs[\u001b[39m2\u001b[39m]\n\u001b[1;32m    193\u001b[0m     \u001b[39m# In any other case, raise the RayActorError as-is.\u001b[39;00m\n\u001b[1;32m    194\u001b[0m     \u001b[39melse\u001b[39;00m:\n\u001b[1;32m    195\u001b[0m         \u001b[39mraise\u001b[39;00m e\n",
      "\u001b[0;31mRaySystemError\u001b[0m: System error: No module named 'core'\ntraceback: Traceback (most recent call last):\n  File \"/home/quanta/.conda/envs/forl-proj/lib/python3.10/site-packages/ray/_private/serialization.py\", line 369, in deserialize_objects\n    obj = self._deserialize_object(data, metadata, object_ref)\n  File \"/home/quanta/.conda/envs/forl-proj/lib/python3.10/site-packages/ray/_private/serialization.py\", line 252, in _deserialize_object\n    return self._deserialize_msgpack_data(data, metadata_fields)\n  File \"/home/quanta/.conda/envs/forl-proj/lib/python3.10/site-packages/ray/_private/serialization.py\", line 207, in _deserialize_msgpack_data\n    python_objects = self._deserialize_pickle5_data(pickle5_data)\n  File \"/home/quanta/.conda/envs/forl-proj/lib/python3.10/site-packages/ray/_private/serialization.py\", line 197, in _deserialize_pickle5_data\n    obj = pickle.loads(in_band)\nModuleNotFoundError: No module named 'core'\n"
     ]
    }
   ],
   "source": [
    "# load checkpoint init weight\n",
    "algo = config.build().load_checkpoint('/home/quanta/ray_results/wolfpack/dqn/DQN_wolfpack_5e5a5_00000_0_2023-05-21_12-22-20/checkpoint_000010')\n",
    "\n",
    "# worker = algo.workers.local_worker()\n",
    "# policy_map = worker.policy_map()\n",
    "# for policy_id in policy_map.keys():\n",
    "#     print(policy_id)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "forl-proj",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.4"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
